version: '3.8'

services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../deployment/docker/backend.Dockerfile
    container_name: jharkhand_prod_backend
    restart: always
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
      - AI_MODE=mock
      - DATABASE_URL=sqlite:///./jharkhand_samadhan.db
      - JWT_SECRET=jharkhand_sih_2026_super_secret_jwt_key_998877
    volumes:
      - prod_uploads:/app/uploads
      - prod_db:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../deployment/docker/frontend.Dockerfile
    container_name: jharkhand_prod_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  prod_uploads:
  prod_db:
