export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi NCR',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const CENTRAL_MINISTRIES = [
  'Ministry of Jal Shakti',
  'Ministry of Road Transport and Highways',
  'Ministry of Agriculture and Farmers Welfare',
  'Ministry of Health and Family Welfare',
  'Ministry of New and Renewable Energy',
  'Ministry of Environment, Forest and Climate Change',
  'Ministry of Rural Development',
  'Ministry of Housing and Urban Affairs',
  'Ministry of Electronics and Information Technology',
  'Ministry of Education',
];

export const PROBLEM_CATEGORIES = [
  'Water & Sanitation',
  'Road & Infrastructure',
  'Agriculture & Irrigation',
  'Rural Healthcare',
  'Clean Energy & Environment',
  'Education & Digital Access',
  'Public Safety & Disaster Management',
  'Urban Governance & Waste Management',
];

export const DEMO_PERSONAS = [
  {
    role: 'citizen',
    label: 'Citizen',
    description: 'Community Reporter',
    icon: 'User',
    email: 'citizen@indiasamadhan.gov.in',
    badgeColor: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
  },
  {
    role: 'student',
    label: 'Student Innovator',
    description: 'IIT/NIT Team Lead',
    icon: 'GraduationCap',
    email: 'student@iitb.ac.in',
    badgeColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  },
  {
    role: 'university',
    label: 'University Dean',
    description: 'R&D Labs & Mentors',
    icon: 'Building2',
    email: 'dean.rnd@iitb.ac.in',
    badgeColor: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  },
  {
    role: 'faculty',
    label: 'Faculty Mentor',
    description: 'Academic Guide',
    icon: 'BookOpen',
    email: 'faculty@iitd.ac.in',
    badgeColor: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30',
  },
  {
    role: 'expert',
    label: 'Domain Expert',
    description: 'CSIR / NABL Scientist',
    icon: 'ShieldCheck',
    email: 'expert@csir-neeri.res.in',
    badgeColor: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  },
  {
    role: 'industry',
    label: 'Industry CSR Lead',
    description: 'Tata / Reliance Fund',
    icon: 'Briefcase',
    email: 'csr@tatatrusts.org',
    badgeColor: 'bg-orange-500/20 text-orange-400 border-orange-500/30',
  },
  {
    role: 'government',
    label: 'Govt Nodal Officer',
    description: 'Ministry Executive Engineer',
    icon: 'Landmark',
    email: 'officer@jalshakti.gov.in',
    badgeColor: 'bg-rose-500/20 text-rose-400 border-rose-500/30',
  },
  {
    role: 'admin',
    label: 'National Admin',
    description: 'Platform Overseer',
    icon: 'Sliders',
    email: 'admin@indiasamadhan.gov.in',
    badgeColor: 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30',
  },
];
